# Common array operations
Now that we've gone through different ways of creating an array, let's go into some of the common array operations like 

In [20]:
import numpy as np

In [21]:
# an array with weight in pounds
array = np.array([140, 174, 166, 192])
array

array([140, 174, 166, 192])

In [22]:
weight_array = np.array([200, 180, 140, 205])

In [23]:
# divide by 2.2 to get values in kilos
array / 2.2

array([63.63636364, 79.09090909, 75.45454545, 87.27272727])

In [24]:
weight_array / 2.2

array([90.90909091, 81.81818182, 63.63636364, 93.18181818])

## Reshaping arrays

In [25]:
array = np.ones((3,4))
array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [36]:
weight_array = np.zeros((2,4))
weight_array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [37]:
array.reshape((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [38]:
weight_array.reshape((4,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [39]:
# reshaping has to keep the same number of items
array.reshape((12,1))

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [40]:
weight_array.reshape((4,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [41]:
# otherwise you get into trouble
array.reshape((5,1))

ValueError: cannot reshape array of size 12 into shape (5,1)

In [42]:
weight_array.reshape((4,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [43]:
# flatten arrays
print(array)
array.flatten()

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [44]:
print(weight_array)
weight_array.flatten()

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


array([0., 0., 0., 0., 0., 0., 0., 0.])