# More array operations


In [65]:
import numpy as np

## Expanding arrays

In [66]:
# create a single dimension array
array = np.ones((4,)) # 4 rows, 1 column
print(array)
print(array.shape)

# expand one row
expanded = array[np.newaxis, :]
expanded.shape

[1. 1. 1. 1.]
(4,)


(1, 4)

In [67]:
# weight_array = np.zeros((4, 1)) # 4 rows, 1 column
weight_array = np.zeros((4, )) # 4 columns, 1 row
print(weight_array)
print(weight_array.shape)

[0. 0. 0. 0.]
(4,)


## Conditional new arrays

In [68]:
array = np.array([[3,12,11],[45,22,11],[56,15,22]])
# represent all matching conditions
print(array < 20)

[[ True  True  True]
 [False False  True]
 [False  True False]]


In [69]:
weight_array = np.array([[1,3,7], [2,4,6], [3,5,7], [4,6,8]])

In [70]:
# produce all matching values
array[array < 20]

array([ 3, 12, 11, 11, 15])

In [71]:
weight_array[weight_array < 5]

array([1, 3, 2, 4, 3, 4])

## Slicing

Similar to Python lists, but with more features and capabilities

In [72]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [73]:
b = np.arange(6, 12) # number value start, stop
b

array([ 6,  7,  8,  9, 10, 11])

In [74]:
# give a range
a[1:4]

array([1, 2, 3])

In [75]:
b[2:5] # array index start, stop

array([ 8,  9, 10])

## Stacking


In [76]:
# horizontally
# must have same number of dimensions!
first = np.full((2, 12), 2)
print(first)
second = np.full((2, 7), 2)
print(second)
np.hstack((first, second))

[[2 2 2 2 2 2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2 2 2 2 2 2]]
[[2 2 2 2 2 2 2]
 [2 2 2 2 2 2 2]]


array([[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]])

In [77]:
# horizontally
# must have same number of dimensions!
nfirst = np.full((2, 8), 7) # 2 rows, 8 columns
print(nfirst)
nsecond = np.full((2, 5), 7) # 2 rows, 5 columns
print(nsecond)
np.hstack((nfirst, nsecond))

[[7 7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7 7]]
[[7 7 7 7 7]
 [7 7 7 7 7]]


array([[7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7]])

In [78]:
# stacking vertically
first = np.full((3,3), 1)
print(first)
second = np.full((3,3), 2)
print(second)
np.vstack((first, second))


[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[2 2 2]
 [2 2 2]
 [2 2 2]]


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [79]:
nfirst = np.full((3,3), 3)
print(nfirst)
nsecond = np.full((3,3), 4)
print(nsecond)
np.vstack((nfirst, nsecond))

[[3 3 3]
 [3 3 3]
 [3 3 3]]
[[4 4 4]
 [4 4 4]
 [4 4 4]]


array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3],
       [4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])


## Splitting arrays

In [80]:
array = np.arange(1, 11)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [81]:
weight_array = np.arange(1, 11)
weight_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [82]:
# split into two equal parts
# warning it needs to allow for an equal division!
np.hsplit(array, 2)


[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]

In [83]:
np.hsplit(weight_array, 2)

[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10])]

In [84]:
# this allows for "unpacking"
first, second = np.hsplit(array, 2)
print(first)
print(second)

[1 2 3 4 5]
[ 6  7  8  9 10]


In [85]:
nfirst, nsecond = np.hsplit(weight_array, 2)
print(nfirst)
print(nsecond)

[1 2 3 4 5]
[ 6  7  8  9 10]
